### PR TITLE
Merge latest gnu gcc 4.7 branch

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pbeeler** [comment]
GCC 4.7 is EOL..

Move onto 4.8 or 4.9

**Comment by ghost** [comment]
I do use gcc 4.8 for compiling platforms, but it seems that some apps FCs with gcc 4.8+ so..

**Comment by pbeeler** [comment]
Goggle uses 4.8 by default on their development branch which indicates
android L will be built with gcc 4.8.  And they released previews for
several devices so app developers can test the new platform which uses art
only (no dalvik), gcc 4.8 and java 7..

You could message the app devs and ask them to update...  If they can't
test a developer preview, they can build on AOSP master to test.  Maybe
email them some logs...

**Comment by pbeeler** [comment]
The 4.7 branch is just for GPL referencing.

**Pull request closed without merging**
