### PR TITLE
Fuck I'm dumb

### PR DESCRIPTION
**Pull request by mydongistiny**
Commit was after fix was already pushed but mine is better please merge!

### CODE REVIEW

**Comment by pbeeler** [comment]
You might want to check the changes next time before sending a pull request.  This was fixed before your pull request.

**Comment by mydongistiny** [comment]
Actually it wasnt. You only fixed one. There where 2 that had extra endif's. Your code is still broken.

**Comment by pbeeler** [comment]
https://github.com/SaberMod/GCC_SaberMod/commit/36294ed55d7577f2f1c99504143d85036390fbe7

**Comment by pbeeler** [comment]
Well I wasn't notified of the pull request before I ammended the change.  I stared this repo so it should notify me by email from now on.

**Comment by pbeeler** [comment]
You still have e the redirect up on the old site but I'm the asshole
right?  Yeah...  Makes sense.

**Comment by mydongistiny** [comment]
Well actually it was back to normal, then you started treating to sue me so I put it back up. If you would have just looked before trying to say you were gonna have it taken down then it would still be normal. So yeah, you're the asshole.

**Comment by pbeeler** [comment]
Uh...  Huh.  So it makes everything better now so we can collaborate on gcc?

**Comment by mydongistiny** [comment]
Hahaha no, but other people use the source. I'm not doing it for you.

**Comment by pbeeler** [comment]
Well that's why we have logs so we can find out what's causing the errors
and fix it.  There is a message on the error reporting to email the log.
We also have lives so we can't get to fixing everything right away.  If
"other" people use the source they can contact through email or hangouts.

**Comment by mydongistiny** [comment]
Well there's also github. That's the point of pull requests. People can come and see if someone else has already found the fix if they can't fix it themselves.

**Comment by pbeeler** [comment]
If you go the network view you can see my commit was before yours, and was
also pushed before yours.

Screens attached:
https://drive.google.com/file/d/0Bxk7Dj4w1Ib8WGlxMUhQdnJqWDg/view?usp=docslist_api

https://drive.google.com/file/d/0Bxk7Dj4w1Ib8S052T0hSRkR2TG8/view?usp=docslist_api


On Thu, Jul 16, 2015, 12:26 AM Jason <notifications@github.com> wrote:

Well there's also github. That's the point of pull requests. People can
come and see if someone else has already found the fix if they can't fix it
themselves.

—
Reply to this email directly or view it on GitHub
<https://github.com/SaberMod/GCC_SaberMod/pull/9#issuecomment-121845642>.

**Comment by mydongistiny** [comment]
Keep telling yourself that if it makes you feel better. Wait till you see what I do with sabermod.net tomorrow. It's gonna be glorious!

**Comment by pbeeler** [comment]
Was already fixed and pushed in 36294ed55d7577f2f1c99504143d85036390fbe7 before this pull request.

**Pull request closed without merging**
